### ISSUE TITLE
Update Project's redme file

### ISSUE THREAD

**Issue by IndigoWizard** [MicroClub-USTHB/Hacktoberfest-2k19#47]
The [Readme file](https://github.com/MicroClub-USTHB/Hacktoberfest-2k19/blob/master/Projects/ProjectsContributionRules.md) in the [_/Projects_](https://github.com/MicroClub-USTHB/Hacktoberfest-2k19/tree/master/Projects) folder needs update:
- Add a summary
- Link to the Topic folders
- Sublist of projects availble
- ... if you got any idea on the enhancement you're welcome to contribute

**Comment by saideepd** [comment]
Hey @IndigoWizard I would like to work on this issue

**Comment by IndigoWizard** [comment]
Great, it's all yours!

**Comment by saideepd** [comment]
Check the **PR #50** I made to the repo
